bitree:bitree_main.c bitree_im.c bitree.h
	gcc -g -o bitree bitree_main.c bitree_im.c

traverse:traverse_main.c traverse_im.c bitree_im.c list_im.c traverse.h
	gcc -g -o traverse traverse_main.c traverse_im.c bitree_im.c list_im.c
